// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKPKmsO7px6fE1R1cs9M7qoUmBmEahrm8',
    appId: '1:593487381206:web:50ec0be4fae1ce55777f77',
    messagingSenderId: '593487381206',
    projectId: 'checkin-256ad',
    authDomain: 'checkin-256ad.firebaseapp.com',
    storageBucket: 'checkin-256ad.firebasestorage.app',
    measurementId: 'G-D79LEKPG7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbX4UjXC2lbG3IG48iGwtyt7pE9dO-I7M',
    appId: '1:593487381206:android:e158e0a516a6ca43777f77',
    messagingSenderId: '593487381206',
    projectId: 'checkin-256ad',
    storageBucket: 'checkin-256ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDli_jEik_C7XuUDleXz4lZzxBalVH2Fag',
    appId: '1:593487381206:ios:b2419fc26ccafdb8777f77',
    messagingSenderId: '593487381206',
    projectId: 'checkin-256ad',
    storageBucket: 'checkin-256ad.firebasestorage.app',
    iosBundleId: 'com.example.checkin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDli_jEik_C7XuUDleXz4lZzxBalVH2Fag',
    appId: '1:593487381206:ios:b2419fc26ccafdb8777f77',
    messagingSenderId: '593487381206',
    projectId: 'checkin-256ad',
    storageBucket: 'checkin-256ad.firebasestorage.app',
    iosBundleId: 'com.example.checkin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKPKmsO7px6fE1R1cs9M7qoUmBmEahrm8',
    appId: '1:593487381206:web:60c911128741f9c2777f77',
    messagingSenderId: '593487381206',
    projectId: 'checkin-256ad',
    authDomain: 'checkin-256ad.firebaseapp.com',
    storageBucket: 'checkin-256ad.firebasestorage.app',
    measurementId: 'G-P90RE99XP8',
  );
}
